In [54]:
# importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [55]:
df = pd.read_csv("data/stud (2).csv")

In [56]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race_ethnicity               1000 non-null   str
 2   parental_level_of_education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test_preparation_course      1000 non-null   str
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [58]:
df.shape

(1000, 8)

In [59]:
df.describe

<bound method NDFrame.describe of      gender race_ethnicity parental_level_of_education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test_preparation_course  math_score  reading_score  writing_score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

In [60]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [61]:
df.duplicated().sum()

np.int64(0)

In [62]:
for col in df.columns:
    print(col)
    print("\n",df[col].value_counts())
    print("="*50)

gender

 gender
female    518
male      482
Name: count, dtype: int64
==================================================
race_ethnicity

 race_ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64
==================================================
parental_level_of_education

 parental_level_of_education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64
==================================================
lunch

 lunch
standard        645
free/reduced    355
Name: count, dtype: int64
==================================================
test_preparation_course

 test_preparation_course
none         642
completed    358
Name: count, dtype: int64
==================================================
math_score

 math_score
65    36
62    35
69    32
59    32
73    27
      ..
24     1
26     1
19     1
23     1
8      1
Name: count, Length: 81, dtype: int64
==================================================
reading_score

 reading_score
72    34
74    33
64    32
73    30
67    30
      ..
17     1
26     1
28     1
23     1
40     1
Name: count, Length: 72, dtype: int64
==================================================
writing_score

 writing_score
74    35
70    33
68    31
73    28
80    27
      ..
19     1
35     1
15     1
30     1
23     1
Name: count, Length: 77, dtype: int64
==================================================

In [63]:
for col in df.columns:
    print(df[col].unique())

<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str
<StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str
<StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str
<StringArray>
['none', 'completed']
Length: 2, dtype: str
[ 72  69  90  47  76  71  88  40  64  38  58  65  78  50  18  46  54  66
  44  74  73  67  70  62  63  56  97  81  75  57  55  53  59  82  77  33
  52   0  79  39  45  60  61  41  49  30  80  42  27  43  68  85  98  87
  51  99  84  91  83  89  22 100  96  94  48  35  34  86  92  37  28  24
  26  95  36  29  32  93  19  23   8]
[ 72  90  95  57  78  83  43  64  60  54  52  81  53  75  89  32  42  58
  69  73  71  74  70  65  87  56  61  84  55  44  41  85  59  17  39  80
  37  63  51  49  26  68  45  47  86  34  79  66  67  91 100  76  77  82
  92  93  62  88  50  28  48  46  23  38  94  97  99  31  96  24  29  40]
[ 74  88  93  44  75  78  92  39  67  50  52  43  73  70  58  86  28  46
  61  63  53  80  72  55  65  38  82  79  83  59  57  54  68  66  62  76
  48  42  87  49  10  34  71  37  56  41  22  81  45  36  89  47  90 100
  64  98  51  40  84  69  33  60  85  91  77  27  94  95  19  35  32  96
  97  99  15  30  23]

In [64]:
numeric_col = [feature for feature in df.columns if df[feature].dtype!='str']
categorical_col = [feature for feature in df.columns if df[feature].dtype=='str']

In [65]:
print("Numeric columns are:", numeric_col)
print("categorical columns are :",categorical_col)

Numeric columns are: ['math_score', 'reading_score', 'writing_score']
categorical columns are : ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [66]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [67]:
X = df.drop("math_score",axis=1)
y = df["math_score"]

In [68]:
le = LabelEncoder()
for col in X.columns:
  if X[col].dtype == "Object":
    X[col] = pd.get_dummies(X,columns=[col],drop_first=False)
  else:
    X[col] = le.fit_transform(X[col]).astype(int)
y = le.fit_transform(y)

In [69]:

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [70]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [71]:
def evaluate_model(true,pred):
    mae= mean_absolute_error(true,pred)
    mse= mean_squared_error(true, pred)
    rmse= np.sqrt(mean_squared_error(true, pred))
    r2 = r2_score(true,pred)
    return mae,mse,rmse,r2

In [72]:
models = {
    'Linear Regression' : LinearRegression(),
    'Ridge Regression' : Ridge(),
    'Lasso Regression' : Lasso(),
    'KNN Regression' : KNeighborsRegressor(),
    'Decision Tree Regressor' : DecisionTreeRegressor(),
    'Random Forest Regressor' : RandomForestRegressor(),
    'XGB Regressor' : XGBRegressor(),
    'CatBoost Regressor' : CatBoostRegressor(verbose=False),
    'AdaBoostRegressor' : AdaBoostRegressor()
}

model_list = []
r2_list = []

for i in range (len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    # make prediction
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # evaluate the model
    mse,mae,rmse,r2=evaluate_model(y_test,y_test_pred)
    mse1,mae1,rmse1,r21 =evaluate_model(y_train,y_train_pred)

    r2_list.append(r2)
    model_list.append(list(models.keys())[i])

In [73]:
print(r2_list)
print(model_list)

[0.8782254771811233, 0.8782759116206955, 0.8492194811405941, 0.7843367942740439, 0.7493654687209743, 0.8447317808893224, 0.8176338076591492, 0.8489501056593132, 0.8483268187631648]
['Linear Regression', 'Ridge Regression', 'Lasso Regression', 'KNN Regression', 'Decision Tree Regressor', 'Random Forest Regressor', 'XGB Regressor', 'CatBoost Regressor', 'AdaBoostRegressor']

In [74]:
pd.DataFrame(r2_list,model_list)

                                0
Linear Regression        0.878225
Ridge Regression         0.878276
Lasso Regression         0.849219
KNN Regression           0.784337
Decision Tree Regressor  0.749365
Random Forest Regressor  0.844732
XGB Regressor            0.817634
CatBoost Regressor       0.848950
AdaBoostRegressor        0.848327

In [76]:
final = LinearRegression()
final.fit(X_train,y_train)

LinearRegression()

In [77]:
final_pred = final.predict(X_test)

In [78]:
acc=r2_score(y_test,final_pred)
final_mse = mean_squared_error(y_test,final_pred)
final_mae = mean_absolute_error(y_test,final_pred)
final_rmse=np.sqrt(mse)

print("Accuracy:", acc)

print("Mean Squared Error:", final_mse)
print("Mean Absolute Error:", final_mae)
print("RMSE",final_rmse)

Accuracy: 0.8782254771811233
Mean Squared Error: 27.876498944811374
Mean Absolute Error: 4.092419014391825
RMSE 2.136119226506984

In [80]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load dataset
df = pd.read_csv("data/stud (2).csv")

# Features and target
X = df.drop("math_score", axis=1)
y = df["math_score"]

# Categorical columns
categorical_columns = [
    "gender",
    "race_ethnicity",
    "parental_level_of_education",
    "lunch",
    "test_preparation_course"
]

# Numerical columns
numerical_columns = [
    "reading_score",
    "writing_score"
]

# Preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_columns
        ),
        (
            "num",
            StandardScaler(),
            numerical_columns
        )
    ]
)

# Complete pipeline
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression())
    ]
)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

# Save complete pipeline
with open("Model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

MAE: 4.214763142474852
MSE: 29.095169866715526
RMSE: 5.393993869732847
R2 Score: 0.8804332983749563
Model saved successfully!

In [81]:
df.columns

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course', 'math_score', 'reading_score',
       'writing_score'],
      dtype='str')